project:
  type: website

website:
  title: "Dona Fácil"
  search: false
  navbar:
    left:
      - href: index.qmd
      - href: exploradonas.qmd
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



